version: "3"
services:
  mysql:
    image: mysql:5.7.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    networks:
      - test-net
    ports:
      - "3306:3306"
networks:
  test-net:
    external:
      name: test-network