spring:
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/test?useUnicode=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: true